services:
  - type: web
    name: openrouter-bot
    runtime: docker
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /health

    numInstances: 1

    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: ADMIN_IDS
        sync: false

      - key: NVIDIA_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false

      - key: PUBLIC_MODE
        value: "true"
      - key: PRIVATE_ACCESS
        value: everyone
      - key: GROUP_ACCESS
        value: everyone
      - key: GROUP_CHAT_MODE
        value: mention
      - key: LANG
        value: EN
      - key: RENDER_MARKDOWN
        value: "false"
      - key: LOGS_DIR
        value: logs

      - key: PORT
        value: "10000"
